repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^saas-backend/
      - id: ruff-format
        files: ^saas-backend/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: \.(svg|ico)$
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        files: ^saas-backend/app/
        additional_dependencies:
          - pydantic>=2
          - sqlalchemy>=2
          - fastapi
          - types-passlib
